name: CI Pipeline

on:
  push:
    branches:
      - 'main'

  # Run on Merge queue
  merge_group:

  # Run CI for any PRs that target 'main' when they are opened or updated.
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize

jobs:
  client-dotnet:
    uses: ./.github/workflows/clients-dotnet.yml
  full-pipeline:
    needs:
      - client-dotnet
    runs-on: ubuntu-latest
    steps:
      - name: All CI Jobs Passed
        working-directory: ./
        run: exit 0
